### ISSUE TITLE
question about benchmark result

### ISSUE THREAD

**Issue by silentred** [kubewharf/kubebrain#42]
I tried to compare kubebrain and etcd v3.5.15, the bencharmk result is not quite as expected. 

benchmark condition:
etcd v3.5.15 on 3 nodes(64C250G)
kubebrain with badger on one same node. I added 10ms sleep to badger batch.Put to simulate KV latency.
```
func (b *batch) Put(key []byte, val []byte, ttl int64) {
	f := func() error {
		if ttl != 0 {
			entry := badger.NewEntry(key, val).WithTTL(time.Duration(ttl) * time.Second)
			return b.txn.SetEntry(entry)
		}
		time.Sleep(10 * time.Millisecond)
		return b.txn.Set(key, val)
	}
	b.list = append(b.list, f)
}
```

benchmark tool operations:
only Create operation, which is txn(Cmp: key.ModRev=0, Success: put key,value)
```
benchmark txn-put --endpoints=xxx --cacert=ca.crt --cert=client.crt --key=client.key --clients 100 --conns 100 --key-size 80 --val-size 2000 --key-space-size 100000 --total 100000
```

results:
etcd v3.5.15
```
Summary:
  Total:	14.8522 secs.
  Slowest:	0.2887 secs.
  Fastest:	0.0098 secs.
  Average:	0.0148 secs.
  Stddev:	0.0058 secs.
  Requests/sec:	6733.0141
```

kubebrain
```
Summary:
  Total:	23.6035 secs.
  Slowest:	0.0455 secs.
  Fastest:	0.0194 secs.
  Average:	0.0236 secs.
  Stddev:	0.0026 secs.
  Requests/sec:	4236.6635
```

---
update: 10ms may be too long
